export const AUTHENTICATED_USER_SUCCESS = "AUTHENTICATED_USER_SUCCESS";
export const AUTHENTICATED_USER_ERROR = "AUTHENTICATED_USER_ERROR";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const FILE_UPLOAD = "FILE_UPLOAD";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";

export const CREATE_LINK_SUCCESS = "CREATE_LINK_SUCCESS";

export const SHOW_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const CLEAR_STATE = "CLEAR_STATE";

export const EDIT_DOWNLOADS = "EDIT_DOWNLOADS";
export const EDIT_HAS_PASSWORD = "EDIT_HAS_PASSWORD";
export const EDIT_PASSWORD = "EDIT_PASSWORD";
export const EDIT_AUTHOR = "EDIT_AUTHOR";
